# Base configs
baseurl: "https://ohhelloworld.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Himanshu Photography"
subtitle: "See the world through my eyes!"
author: "Himanshu"
header:
 title: "Photography"
 subtitle: "by Himanshu"
footer:
 name: "Hey there, my name is Himanshu"
 bio: "Welcome to this website which is dedicated to my Photography only. For more information about me, please visit - himanshugoel.in"
 github: ""
web_design: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
